const fs = require("fs");
const path = require("path");
const { writeProjectFile, pathInPackage } = require("./fs");

function toPackageName(rawName) {
  const safe = String(rawName || "my-plugin")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_/@]+/g, "-")
    .replace(/^-+|-+$/g, "");

  if (safe.startsWith("@rarog/")) return safe;
  if (safe.startsWith("rarog-plugin-")) return safe;
  return `@rarog/plugin-${safe.replace(/^plugin-/, "")}`;
}

function toFolderName(packageName) {
  return packageName
    .replace(/^@rarog\//, "")
    .replace(/[^a-z0-9-_]+/g, "-");
}

function createRarogPluginStarter(options = {}) {
  const packageName = toPackageName(options.name || "my-plugin");
  const folderName = options.dir || path.join("plugins", toFolderName(packageName));
  const starterTemplatePath = pathInPackage("packages/plugin-sdk/templates/starter/index.cjs");
  const starterTemplate = fs.readFileSync(starterTemplatePath, "utf8");
  const outputPath = path.join(folderName, "index.cjs");
  const readmePath = path.join(folderName, "README.md");
  const testPath = path.join(folderName, "plugin.test.cjs");

  writeProjectFile(
    outputPath,
    starterTemplate.replace(/@rarog\/plugin-my-plugin/g, packageName)
  );

  writeProjectFile(
    readmePath,
    `# ${packageName}\n\nGenerated by \`create-rarog-plugin\`.\n\n## Usage\n\n\
module.exports = {\n  plugins: [require("./${path.posix.join(folderName.replace(/\\/g, "/"), "index.cjs")}")]\n};\n\
\n## Test\n\nUse \`createPluginTestHarness()\` from \`packages/plugin-sdk/index.cjs\` to validate compatibility and CSS output.\n`
  );

  writeProjectFile(
    testPath,
    `const { describe, it, expect } = require("vitest");\nconst { createPluginTestHarness } = require("../../packages/plugin-sdk/index.cjs");\nconst plugin = require("./index.cjs");\n\ndescribe("${packageName}", () => {\n  it("returns css", () => {\n    const harness = createPluginTestHarness({ rarogVersion: "1.0.0", rootDir: process.cwd() });\n    const execution = harness.execute(plugin, { config: { mode: "jit" } });\n    expect(execution.result.utilitiesCss).toContain("plugin-my-plugin-stack");\n  });\n});\n`
  );

  return {
    packageName,
    folderName,
    files: [outputPath, readmePath, testPath]
  };
}

module.exports = {
  createRarogPluginStarter
};
