const fs = require('fs');
const path = require('path');
const { pathInProject, writeProjectFile } = require('./fs');
const { getEffectiveConfig } = require('./config');

const REQUIRED_SEMANTIC_KEYS = [
  'bg', 'bgSoft', 'bgElevated', 'bgElevatedSoft', 'surface',
  'border', 'borderSubtle', 'borderStrong', 'muted',
  'text', 'textMuted', 'focusRing', 'accentSoft'
];

const REQUIRED_RUNTIME_SCALES = ['density', 'shape', 'shadow'];

function isObject(value) {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

function deepMerge(base, extra) {
  const result = Array.isArray(base) ? base.slice() : { ...base };
  if (!isObject(extra)) return result;
  for (const key of Object.keys(extra)) {
    const baseValue = result[key];
    const nextValue = extra[key];
    if (isObject(baseValue) && isObject(nextValue)) result[key] = deepMerge(baseValue, nextValue);
    else result[key] = nextValue;
  }
  return result;
}

function relativeProjectPath(filePath) {
  return path.relative(process.cwd(), filePath) || path.basename(filePath);
}

function createBaseThemeManifest() {
  const effective = getEffectiveConfig();
  return {
    $schema: 'https://rarog.dev/schema/theme-manifest-v1.json',
    version: 1,
    name: 'custom-theme',
    extends: 'default',
    meta: {
      mode: 'light',
      brand: 'acme',
      description: 'Rarog theme manifest generated by rarog theme create'
    },
    raw: {
      color: {
        primary: effective.theme.colors.primary,
        secondary: effective.theme.colors.secondary
      },
      spacing: effective.theme.spacing,
      radius: effective.theme.radius,
      shadow: effective.theme.shadow
    },
    semantic: {
      color: {
        ...effective.theme.colors.semantic,
        primary: 'var(--rarog-color-primary-600)',
        primaryForeground: '#ffffff',
        secondary: 'var(--rarog-color-secondary-600)',
        secondaryForeground: '#ffffff'
      }
    },
    component: {
      button: {
        radius: '{shape.control}',
        paddingInline: '{density.controlX}',
        shadow: '{shadow.sm}'
      },
      card: {
        radius: '{shape.surface}',
        shadow: '{shadow.md}',
        background: '{semantic.color.surface}'
      },
      input: {
        radius: '{shape.control}',
        borderColor: '{semantic.color.border}',
        focusRing: '{semantic.color.focusRing}'
      }
    },
    runtime: {
      density: {
        compact: { controlX: '0.625rem', controlY: '0.375rem', panelGap: '0.75rem' },
        comfortable: { controlX: '0.875rem', controlY: '0.625rem', panelGap: '1rem' },
        spacious: { controlX: '1rem', controlY: '0.75rem', panelGap: '1.25rem' }
      },
      shape: {
        sharp: { control: '0.375rem', surface: '0.75rem', pill: '9999px' },
        soft: { control: '0.75rem', surface: '1rem', pill: '9999px' },
        rounded: { control: '1rem', surface: '1.25rem', pill: '9999px' }
      },
      shadow: {
        subtle: { sm: '0 1px 2px rgba(15,23,42,.08)', md: '0 6px 12px rgba(15,23,42,.12)' },
        balanced: { sm: '0 2px 4px rgba(15,23,42,.12)', md: '0 12px 24px rgba(15,23,42,.16)' },
        dramatic: { sm: '0 8px 18px rgba(15,23,42,.18)', md: '0 18px 40px rgba(15,23,42,.24)' }
      }
    },
    selectors: {
      root: ':root',
      scoped: '[data-rg-theme="custom-theme"]'
    }
  };
}

function loadThemeManifest(inputPath) {
  const absPath = path.isAbsolute(inputPath) ? inputPath : pathInProject(inputPath);
  return JSON.parse(fs.readFileSync(absPath, 'utf8'));
}

function flatten(obj, prefix = '', out = {}) {
  if (!isObject(obj)) return out;
  for (const key of Object.keys(obj)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;
    const value = obj[key];
    if (isObject(value)) flatten(value, nextKey, out);
    else out[nextKey] = value;
  }
  return out;
}

function validateThemeManifest(theme, label = 'theme') {
  const errors = [];
  const warnings = [];
  if (!isObject(theme)) errors.push(`${label}: manifest must be an object`);
  if (!theme.name) warnings.push(`${label}: name is missing`);
  const semantic = theme.semantic && theme.semantic.color;
  if (!isObject(semantic)) {
    errors.push(`${label}: semantic.color block is required`);
  } else {
    REQUIRED_SEMANTIC_KEYS.forEach((key) => {
      if (semantic[key] == null) errors.push(`${label}: semantic.color.${key} is required`);
    });
  }
  const runtime = theme.runtime || {};
  REQUIRED_RUNTIME_SCALES.forEach((key) => {
    if (!isObject(runtime[key])) warnings.push(`${label}: runtime.${key} scale is missing`);
  });
  return { valid: errors.length === 0, errors, warnings };
}

function diffThemeManifests(baseTheme, nextTheme) {
  const baseFlat = flatten(baseTheme);
  const nextFlat = flatten(nextTheme);
  const keys = Array.from(new Set([...Object.keys(baseFlat), ...Object.keys(nextFlat)])).sort();
  const changes = [];
  for (const key of keys) {
    const before = baseFlat[key];
    const after = nextFlat[key];
    if (before === after) continue;
    changes.push({ key, before, after, kind: before === undefined ? 'added' : after === undefined ? 'removed' : 'changed' });
  }
  return changes;
}

function createThemeFile(outputRel, options = {}) {
  const manifest = createBaseThemeManifest();
  if (options.name) manifest.name = options.name;
  if (options.extendsTheme) manifest.extends = options.extendsTheme;
  writeProjectFile(outputRel, JSON.stringify(manifest, null, 2) + '\n');
  return pathInProject(outputRel);
}

function themeToRuntimeCss(theme) {
  const selector = (theme.selectors && theme.selectors.scoped) || (theme.name ? `[data-rg-theme="${theme.name}"]` : ':root');
  const semantic = (theme.semantic && theme.semantic.color) || {};
  const lines = [ `${selector} {` ];
  const mapping = {
    bg: '--rarog-color-bg', bgSoft: '--rarog-color-bg-soft', bgElevated: '--rarog-color-bg-elevated',
    bgElevatedSoft: '--rarog-color-bg-elevated-soft', surface: '--rarog-color-surface',
    border: '--rarog-color-border', borderSubtle: '--rarog-color-border-subtle', borderStrong: '--rarog-color-border-strong',
    muted: '--rarog-color-muted', text: '--rarog-color-text', textMuted: '--rarog-color-text-muted',
    focusRing: '--rarog-color-focus-ring', accentSoft: '--rarog-color-accent-soft',
    primary: '--rarog-color-primary', primaryForeground: '--rarog-color-primary-foreground',
    secondary: '--rarog-color-secondary', secondaryForeground: '--rarog-color-secondary-foreground'
  };
  Object.keys(mapping).forEach((key) => {
    if (semantic[key] != null) lines.push(`  ${mapping[key]}: ${semantic[key]};`);
  });
  const defaultDensity = theme.runtime && theme.runtime.density && (theme.runtime.density.comfortable || Object.values(theme.runtime.density)[0]);
  const defaultShape = theme.runtime && theme.runtime.shape && (theme.runtime.shape.soft || Object.values(theme.runtime.shape)[0]);
  const defaultShadow = theme.runtime && theme.runtime.shadow && (theme.runtime.shadow.balanced || Object.values(theme.runtime.shadow)[0]);
  if (defaultDensity) {
    Object.entries(defaultDensity).forEach(([key, value]) => lines.push(`  --rarog-density-${key}: ${value};`));
  }
  if (defaultShape) {
    Object.entries(defaultShape).forEach(([key, value]) => lines.push(`  --rarog-shape-${key}: ${value};`));
  }
  if (defaultShadow) {
    Object.entries(defaultShadow).forEach(([key, value]) => lines.push(`  --rarog-shadow-runtime-${key}: ${value};`));
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

module.exports = {
  REQUIRED_SEMANTIC_KEYS,
  createBaseThemeManifest,
  loadThemeManifest,
  validateThemeManifest,
  diffThemeManifests,
  createThemeFile,
  themeToRuntimeCss,
  deepMerge,
  relativeProjectPath
};
