const { createPlugin } = require("../../index.cjs");

module.exports = createPlugin({
  name: "@rarog/plugin-my-plugin",
  version: "0.1.0",
  description: "Starter plugin generated by create-rarog-plugin.",
  engine: {
    rarog: ">=1.0.0 <2.0.0"
  },
  capabilities: {
    utilities: true,
    components: true,
    diagnostics: true
  },
  setup(ctx) {
    const diagnostics = [];

    if ((ctx.config.mode || "jit") !== "jit") {
      diagnostics.push({
        level: "info",
        message: "This starter plugin is optimized for JIT mode but remains compatible with full mode."
      });
    }

    return {
      utilitiesCss: `
.plugin-my-plugin-stack {
  display: grid;
  gap: var(--rarog-spacing-3, 0.75rem);
}
`,
      componentsCss: `
.plugin-my-plugin-card {
  border: 1px solid var(--rarog-color-semantic-border, #e5e7eb);
  border-radius: var(--rarog-radius-lg, 0.75rem);
  background: var(--rarog-color-semantic-bgSoft, #ffffff);
  padding: var(--rarog-spacing-4, 1rem);
}
`,
      diagnostics
    };
  }
});
