name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build core assets
        run: npm run build

      - name: Build adapters
        run: npm run build:adapters

      - name: Pack adapters
        run: npm pack ./packages/react && npm pack ./packages/vue

      - name: Publish @rarog/react
        run: npm publish ./packages/react --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @rarog/vue
        run: npm publish ./packages/vue --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
